services:
  db:
    image: postgres:17
    container_name: ida_db
    restart: always
    environment:
      POSTGRES_DB: ida_db
      POSTGRES_USER: ida_admin
      POSTGRES_PASSWORD: ida_password
    ports:
      - "5434:5432"
    volumes:
      - ida_postgres_data:/var/lib/postgresql/data

volumes:
  ida_postgres_data:
