CREATE TABLE ida.cliente_cargo (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCliente" bigint NOT NULL,
    "IdCargo" bigint NOT NULL,
    "DtUltimaAtualizacao" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_cliente_cargo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_cliente_cargo_cargo_IdCargo" FOREIGN KEY ("IdCargo") REFERENCES ida.cargo ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_cliente_cargo_cliente_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES ida.cliente ("Id") ON DELETE CASCADE
);

CREATE TABLE ida.cargo_area (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCargo" bigint NOT NULL,
    "IdArea" bigint NOT NULL,
    "DtUltimaAtualizacao" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_cargo_area" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_cargo_area_area_IdArea" FOREIGN KEY ("IdArea") REFERENCES ida.area ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_cargo_area_cargo_IdCargo" FOREIGN KEY ("IdCargo") REFERENCES ida.cargo ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_cliente_cargo_IdCargo" ON ida.cliente_cargo ("IdCargo");
CREATE INDEX "IX_cliente_cargo_IdCliente" ON ida.cliente_cargo ("IdCliente");
CREATE INDEX "IX_cargo_area_IdArea" ON ida.cargo_area ("IdArea");
CREATE INDEX "IX_cargo_area_IdCargo" ON ida.cargo_area ("IdCargo");

ALTER TABLE ida.area DROP COLUMN "IdCliente" CASCADE;
