// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308183346_AddInvestmentControl")]
    partial class AddInvestmentControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ida")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7766),
                            Nome = "Página Inicial"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7767),
                            Nome = "Dashboard"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7768),
                            Nome = "Gerenciamento de Cliente"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7769),
                            Nome = "Gerenciamento de Pessoa"
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7770),
                            Nome = "Gerenciamento de Cargo"
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7771),
                            Nome = "Gerenciamento de Área"
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7772),
                            Nome = "Gerenciamento de Usuário"
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7773),
                            Nome = "Relatórios"
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7774),
                            Nome = "Configurações"
                        },
                        new
                        {
                            Id = 10L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7774),
                            Nome = "Gerenciamento de Modelo de Controle"
                        },
                        new
                        {
                            Id = 11L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7775),
                            Nome = "Gerenciamento de Lançamentos"
                        },
                        new
                        {
                            Id = 12L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7776),
                            Nome = "Gerenciamento de Investimentos"
                        });
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(8024),
                            Nome = "Administração"
                        });
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7991),
                            IdRole = 1L,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCargo");

                    b.ToTable("cargo_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(8108),
                            IdArea = 1L,
                            IdCargo = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.ToTable("cliente", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cnpj = "00000000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7946),
                            Email = "suporte@analytica.com",
                            Nome = "Analytica IDA",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(8083),
                            IdCargo = 1L,
                            IdCliente = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteInvestimentoGoogle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("VlrInvestimentoGoogle")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 2)
                        .HasColumnType("decimal(38,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("vlr_investimento_google");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_investimento_google", "ida");
                });

            modelBuilder.Entity("backend.Models.ClienteInvestimentoMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("VlrInvestimentoMeta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 2)
                        .HasColumnType("decimal(38,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("vlr_investimento_meta");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_investimento_meta", "ida");
                });

            modelBuilder.Entity("backend.Models.ClienteModeloControle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdModeloControle")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdModeloControle");

                    b.ToTable("cliente_modelo_controle", "ida");
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("cliente_usuario", "ida");
                });

            modelBuilder.Entity("backend.Models.Lancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_lancamento")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdModeloControle")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modelo_controle");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdModeloControle");

                    b.HasIndex("IdUsuario");

                    b.ToTable("lancamento", "ida");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosAntigos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("log_auditoria", "ida");
                });

            modelBuilder.Entity("backend.Models.ModeloControle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("modelo_controle", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7823),
                            Nome = "Cadastros"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7826),
                            Nome = "Varejo"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7827),
                            Nome = "Saúde"
                        });
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdUsuarioDestino")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("notificacao", "ida");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("pessoa", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = "00000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(8135),
                            Email = "suporte@analytica.com",
                            IdCliente = 1L,
                            Nome = "Administrador",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("role", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7526),
                            Nome = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7530),
                            Nome = "proprietário"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7531),
                            Nome = "supervisor"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7532),
                            Nome = "vendedor"
                        });
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdAplicacao")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdRole");

                    b.ToTable("role_aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7865),
                            IdAplicacao = 1L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7868),
                            IdAplicacao = 2L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7868),
                            IdAplicacao = 3L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7869),
                            IdAplicacao = 4L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7870),
                            IdAplicacao = 5L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7871),
                            IdAplicacao = 6L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7876),
                            IdAplicacao = 7L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7876),
                            IdAplicacao = 8L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7877),
                            IdAplicacao = 9L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 25L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7878),
                            IdAplicacao = 10L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 29L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7879),
                            IdAplicacao = 11L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 30L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7879),
                            IdAplicacao = 12L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 10L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7880),
                            IdAplicacao = 1L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 11L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7881),
                            IdAplicacao = 2L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 12L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7881),
                            IdAplicacao = 4L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 13L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7882),
                            IdAplicacao = 5L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 14L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7883),
                            IdAplicacao = 6L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 15L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7884),
                            IdAplicacao = 7L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 16L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7884),
                            IdAplicacao = 8L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 26L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7885),
                            IdAplicacao = 11L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 17L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7886),
                            IdAplicacao = 1L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 18L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7887),
                            IdAplicacao = 2L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 19L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7887),
                            IdAplicacao = 4L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 20L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7888),
                            IdAplicacao = 7L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 21L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7889),
                            IdAplicacao = 8L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 27L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7889),
                            IdAplicacao = 11L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 22L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7890),
                            IdAplicacao = 1L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 23L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7891),
                            IdAplicacao = 2L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 24L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7892),
                            IdAplicacao = 8L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 28L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 191, DateTimeKind.Utc).AddTicks(7892),
                            IdAplicacao = 11L,
                            IdRole = 4L
                        });
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.ToTable("usuario", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 15, 33, 45, 191, DateTimeKind.Local).AddTicks(8178),
                            FlAtivo = true,
                            IdCargo = 1L,
                            Login = "admin",
                            Senha = "$2a$11$eTZFk9JgfWf86mQjyYCrUeNsx2V1fr5F/qLzuHDscQ/L9YfSjUFZm"
                        });
                });

            modelBuilder.Entity("backend.Models.UsuarioArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 8, 18, 33, 45, 633, DateTimeKind.Utc).AddTicks(190),
                            IdArea = 1L,
                            IdUsuario = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.LancamentoCadastro", b =>
                {
                    b.HasBaseType("backend.Models.Lancamento");

                    b.Property<long?>("IdClienteInvestimentoGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente_investimento_google");

                    b.Property<long?>("IdClienteInvestimentoMeta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente_investimento_meta");

                    b.Property<long>("QtdCadastros")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_cadastros");

                    b.Property<long>("QtdClickLink")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_click_link");

                    b.Property<decimal>("VlrTicketMedio")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_ticket_medio");

                    b.HasIndex("IdClienteInvestimentoGoogle");

                    b.HasIndex("IdClienteInvestimentoMeta");

                    b.ToTable("lancamento_cadastro", "ida");
                });

            modelBuilder.Entity("backend.Models.LancamentoSaude", b =>
                {
                    b.HasBaseType("backend.Models.Lancamento");

                    b.Property<long?>("IdClienteInvestimentoGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente_investimento_google");

                    b.Property<long?>("IdClienteInvestimentoMeta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente_investimento_meta");

                    b.Property<long>("QtdClickGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_click_google");

                    b.Property<long>("QtdClickMeta")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_click_meta");

                    b.Property<long>("QtdContatosReais")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_contatos_reais");

                    b.Property<long>("QtdConversaoConsultas")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_conversao_consultas");

                    b.Property<long>("QtdEntradaGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_entrada_google");

                    b.Property<long>("QtdEntradaRedesSociais")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_entrada_redes_sociais");

                    b.Property<decimal?>("VlrTicketMedioConsultas")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_ticket_medio_consultas");

                    b.HasIndex("IdClienteInvestimentoGoogle");

                    b.HasIndex("IdClienteInvestimentoMeta");

                    b.ToTable("lancamento_saude", "ida");
                });

            modelBuilder.Entity("backend.Models.LancamentoVarejo", b =>
                {
                    b.HasBaseType("backend.Models.Lancamento");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("faturamento");

                    b.Property<long?>("IdClienteInvestimentoGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente_investimento_google");

                    b.Property<long?>("IdClienteInvestimentoMeta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente_investimento_meta");

                    b.Property<long>("QtdAtendimento")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_atendimento");

                    b.Property<long>("QtdFacebook")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_facebook");

                    b.Property<long>("QtdFechamento")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_fechamento");

                    b.Property<long>("QtdGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_google");

                    b.Property<long>("QtdIndicacao")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_indicacao");

                    b.Property<long>("QtdInstagram")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_instagram");

                    b.HasIndex("IdClienteInvestimentoGoogle");

                    b.HasIndex("IdClienteInvestimentoMeta");

                    b.ToTable("lancamento_varejo", "ida");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("Cargos")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.ClienteInvestimentoGoogle", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.ClienteInvestimentoMeta", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.ClienteModeloControle", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ModeloControle", "ModeloControle")
                        .WithMany("ClientesModelosControles")
                        .HasForeignKey("IdModeloControle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ModeloControle");
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Lancamento", b =>
                {
                    b.HasOne("backend.Models.ModeloControle", "ModeloControle")
                        .WithMany()
                        .HasForeignKey("IdModeloControle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloControle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.HasOne("backend.Models.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.HasOne("backend.Models.Aplicacao", "Aplicacao")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdAplicacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("backend.Models.Usuario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("backend.Models.UsuarioArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("UsuariosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("UsuariosAreas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.LancamentoCadastro", b =>
                {
                    b.HasOne("backend.Models.Lancamento", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.LancamentoCadastro", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ClienteInvestimentoGoogle", "ClienteInvestimentoGoogle")
                        .WithMany()
                        .HasForeignKey("IdClienteInvestimentoGoogle");

                    b.HasOne("backend.Models.ClienteInvestimentoMeta", "ClienteInvestimentoMeta")
                        .WithMany()
                        .HasForeignKey("IdClienteInvestimentoMeta");

                    b.Navigation("ClienteInvestimentoGoogle");

                    b.Navigation("ClienteInvestimentoMeta");
                });

            modelBuilder.Entity("backend.Models.LancamentoSaude", b =>
                {
                    b.HasOne("backend.Models.Lancamento", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.LancamentoSaude", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ClienteInvestimentoGoogle", "ClienteInvestimentoGoogle")
                        .WithMany()
                        .HasForeignKey("IdClienteInvestimentoGoogle");

                    b.HasOne("backend.Models.ClienteInvestimentoMeta", "ClienteInvestimentoMeta")
                        .WithMany()
                        .HasForeignKey("IdClienteInvestimentoMeta");

                    b.Navigation("ClienteInvestimentoGoogle");

                    b.Navigation("ClienteInvestimentoMeta");
                });

            modelBuilder.Entity("backend.Models.LancamentoVarejo", b =>
                {
                    b.HasOne("backend.Models.Lancamento", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.LancamentoVarejo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ClienteInvestimentoGoogle", "ClienteInvestimentoGoogle")
                        .WithMany()
                        .HasForeignKey("IdClienteInvestimentoGoogle");

                    b.HasOne("backend.Models.ClienteInvestimentoMeta", "ClienteInvestimentoMeta")
                        .WithMany()
                        .HasForeignKey("IdClienteInvestimentoMeta");

                    b.Navigation("ClienteInvestimentoGoogle");

                    b.Navigation("ClienteInvestimentoMeta");
                });

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("UsuariosAreas");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("ClientesCargos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("ClientesCargos");

                    b.Navigation("ClientesUsuarios");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("backend.Models.ModeloControle", b =>
                {
                    b.Navigation("ClientesModelosControles");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("ClientesUsuarios");

                    b.Navigation("UsuariosAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
