// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225130409_AddUsuarioAreaRelationship")]
    partial class AddUsuarioAreaRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ida")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7897),
                            Nome = "Página Inicial"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7898),
                            Nome = "Dashboard"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7899),
                            Nome = "Gerenciamento de Cliente"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7900),
                            Nome = "Gerenciamento de Pessoa"
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7901),
                            Nome = "Gerenciamento de Cargo"
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7902),
                            Nome = "Gerenciamento de Área"
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7903),
                            Nome = "Gerenciamento de Usuário"
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7904),
                            Nome = "Relatórios"
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7905),
                            Nome = "Configurações"
                        });
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(8117),
                            Nome = "Administração"
                        });
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(8086),
                            IdRole = 1L,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCargo");

                    b.ToTable("cargo_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(8167),
                            IdArea = 1L,
                            IdCargo = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.ToTable("cliente", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cnpj = "00000000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(8045),
                            Email = "suporte@analytica.com",
                            Nome = "Analytica IDA",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(8140),
                            IdCargo = 1L,
                            IdCliente = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("cliente_usuario", "ida");
                });

            modelBuilder.Entity("backend.Models.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosAntigos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("log_auditoria", "ida");
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdUsuarioDestino")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("notificacao", "ida");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("pessoa", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = "00000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(8190),
                            Email = "suporte@analytica.com",
                            IdCliente = 1L,
                            Nome = "Administrador",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("role", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7674),
                            Nome = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7678),
                            Nome = "proprietário"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7679),
                            Nome = "supervisor"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7680),
                            Nome = "vendedor"
                        });
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdAplicacao")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdRole");

                    b.ToTable("role_aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7947),
                            IdAplicacao = 1L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7949),
                            IdAplicacao = 2L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7949),
                            IdAplicacao = 3L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7950),
                            IdAplicacao = 4L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7951),
                            IdAplicacao = 5L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7951),
                            IdAplicacao = 6L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7952),
                            IdAplicacao = 7L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7953),
                            IdAplicacao = 8L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7954),
                            IdAplicacao = 9L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 10L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7954),
                            IdAplicacao = 1L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 11L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7955),
                            IdAplicacao = 2L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 12L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7956),
                            IdAplicacao = 4L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 13L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7962),
                            IdAplicacao = 5L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 14L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7963),
                            IdAplicacao = 6L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 15L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7963),
                            IdAplicacao = 7L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 16L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7964),
                            IdAplicacao = 8L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 17L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7965),
                            IdAplicacao = 1L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 18L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7966),
                            IdAplicacao = 2L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 19L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7966),
                            IdAplicacao = 4L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 20L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7967),
                            IdAplicacao = 7L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 21L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7968),
                            IdAplicacao = 8L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 22L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7969),
                            IdAplicacao = 1L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 23L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7970),
                            IdAplicacao = 2L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 24L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 508, DateTimeKind.Utc).AddTicks(7970),
                            IdAplicacao = 8L,
                            IdRole = 4L
                        });
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.ToTable("usuario", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 10, 4, 7, 508, DateTimeKind.Local).AddTicks(8223),
                            FlAtivo = true,
                            IdCargo = 1L,
                            Login = "admin",
                            Senha = "$2a$11$nXITcqG8EvxWXBF3jXU4MeIuEdAjDMY7CveWkAPcZBRzkQOnvGvdi"
                        });
                });

            modelBuilder.Entity("backend.Models.UsuarioArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 25, 13, 4, 7, 644, DateTimeKind.Utc).AddTicks(6064),
                            IdArea = 1L,
                            IdUsuario = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("Cargos")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.HasOne("backend.Models.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.HasOne("backend.Models.Aplicacao", "Aplicacao")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdAplicacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("backend.Models.Usuario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("backend.Models.UsuarioArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("UsuariosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("UsuariosAreas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("UsuariosAreas");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("ClientesCargos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("ClientesCargos");

                    b.Navigation("ClientesUsuarios");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("ClientesUsuarios");

                    b.Navigation("UsuariosAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
