// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304213522_CreateLancamentos")]
    partial class CreateLancamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ida")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6010),
                            Nome = "Página Inicial"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6012),
                            Nome = "Dashboard"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6014),
                            Nome = "Gerenciamento de Cliente"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6015),
                            Nome = "Gerenciamento de Pessoa"
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6016),
                            Nome = "Gerenciamento de Cargo"
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6018),
                            Nome = "Gerenciamento de Área"
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6019),
                            Nome = "Gerenciamento de Usuário"
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6020),
                            Nome = "Relatórios"
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6022),
                            Nome = "Configurações"
                        },
                        new
                        {
                            Id = 10L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6023),
                            Nome = "Gerenciamento de Modelo de Controle"
                        },
                        new
                        {
                            Id = 11L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6024),
                            Nome = "Gerenciamento de Lançamentos"
                        });
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6577),
                            Nome = "Administração"
                        });
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6504),
                            IdRole = 1L,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCargo");

                    b.ToTable("cargo_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6686),
                            IdArea = 1L,
                            IdCargo = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.ToTable("cliente", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cnpj = "00000000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6417),
                            Email = "suporte@analytica.com",
                            Nome = "Analytica IDA",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6628),
                            IdCargo = 1L,
                            IdCliente = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteModeloControle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdModeloControle")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdModeloControle");

                    b.ToTable("cliente_modelo_controle", "ida");
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("cliente_usuario", "ida");
                });

            modelBuilder.Entity("backend.Models.Lancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_lancamento")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdModeloControle")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modelo_controle");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdModeloControle");

                    b.HasIndex("IdUsuario");

                    b.ToTable("lancamento", "ida");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosAntigos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("log_auditoria", "ida");
                });

            modelBuilder.Entity("backend.Models.ModeloControle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("modelo_controle", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6095),
                            Nome = "Cadastros"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6098),
                            Nome = "Varejo"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6100),
                            Nome = "Saúde"
                        });
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdUsuarioDestino")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("notificacao", "ida");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("pessoa", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = "00000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6736),
                            Email = "suporte@analytica.com",
                            IdCliente = 1L,
                            Nome = "Administrador",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("role", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(5553),
                            Nome = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(5560),
                            Nome = "proprietário"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(5562),
                            Nome = "supervisor"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(5563),
                            Nome = "vendedor"
                        });
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdAplicacao")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdRole");

                    b.ToTable("role_aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6157),
                            IdAplicacao = 1L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6160),
                            IdAplicacao = 2L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6161),
                            IdAplicacao = 3L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6162),
                            IdAplicacao = 4L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6163),
                            IdAplicacao = 5L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6165),
                            IdAplicacao = 6L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6166),
                            IdAplicacao = 7L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6280),
                            IdAplicacao = 8L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6282),
                            IdAplicacao = 9L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 25L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6284),
                            IdAplicacao = 10L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 10L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6285),
                            IdAplicacao = 1L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 11L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6287),
                            IdAplicacao = 2L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 12L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6288),
                            IdAplicacao = 4L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 13L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6290),
                            IdAplicacao = 5L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 14L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6291),
                            IdAplicacao = 6L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 15L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6292),
                            IdAplicacao = 7L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 16L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6294),
                            IdAplicacao = 8L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 26L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6295),
                            IdAplicacao = 11L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 17L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6297),
                            IdAplicacao = 1L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 18L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6298),
                            IdAplicacao = 2L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 19L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6299),
                            IdAplicacao = 4L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 20L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6301),
                            IdAplicacao = 7L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 21L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6302),
                            IdAplicacao = 8L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 27L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6303),
                            IdAplicacao = 11L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 22L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6305),
                            IdAplicacao = 1L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 23L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6306),
                            IdAplicacao = 2L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 24L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6307),
                            IdAplicacao = 8L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 28L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 312, DateTimeKind.Utc).AddTicks(6309),
                            IdAplicacao = 11L,
                            IdRole = 4L
                        });
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.ToTable("usuario", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 18, 35, 20, 312, DateTimeKind.Local).AddTicks(6838),
                            FlAtivo = true,
                            IdCargo = 1L,
                            Login = "admin",
                            Senha = "$2a$11$4lcKKjQuzLOhmwgOfqGgj.5wjErCze5RPhPVxa6BLMzqQ41PSNqxa"
                        });
                });

            modelBuilder.Entity("backend.Models.UsuarioArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 3, 4, 21, 35, 20, 534, DateTimeKind.Utc).AddTicks(3654),
                            IdArea = 1L,
                            IdUsuario = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.LancamentoCadastro", b =>
                {
                    b.HasBaseType("backend.Models.Lancamento");

                    b.Property<long>("QtdCadastros")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_cadastros");

                    b.Property<long>("QtdClickLink")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_click_link");

                    b.Property<decimal>("VlrInvestimentoGoogle")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_investimento_google");

                    b.Property<decimal>("VlrInvestimentoMeta")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_investimento_meta");

                    b.Property<decimal>("VlrTicketMedio")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_ticket_medio");

                    b.ToTable("lancamento_cadastro", "ida");
                });

            modelBuilder.Entity("backend.Models.LancamentoSaude", b =>
                {
                    b.HasBaseType("backend.Models.Lancamento");

                    b.Property<long>("QtdClickGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_click_google");

                    b.Property<long>("QtdClickMeta")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_click_meta");

                    b.Property<long>("QtdContatosReais")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_contatos_reais");

                    b.Property<long>("QtdConversaoConsultas")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_conversao_consultas");

                    b.Property<long>("QtdEntradaGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_entrada_google");

                    b.Property<long>("QtdEntradaRedesSociais")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_entrada_redes_sociais");

                    b.Property<decimal?>("VlrInvestimentoGoogle")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_investimento_google");

                    b.Property<decimal?>("VlrInvestimentoMeta")
                        .HasColumnType("numeric(38,12)")
                        .HasColumnName("vlr_investimento_meta");

                    b.Property<decimal?>("VlrTicketMedioConsultas")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_ticket_medio_consultas");

                    b.ToTable("lancamento_saude", "ida");
                });

            modelBuilder.Entity("backend.Models.LancamentoVarejo", b =>
                {
                    b.HasBaseType("backend.Models.Lancamento");

                    b.Property<decimal>("Faturamento")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("faturamento");

                    b.Property<long>("QtdAtendimento")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_atendimento");

                    b.Property<long>("QtdFacebook")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_facebook");

                    b.Property<long>("QtdFechamento")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_fechamento");

                    b.Property<long>("QtdGoogle")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_google");

                    b.Property<long>("QtdIndicacao")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_indicacao");

                    b.Property<long>("QtdInstagram")
                        .HasColumnType("bigint")
                        .HasColumnName("qtd_instagram");

                    b.Property<decimal>("VlrInvestimentoGoogle")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_investimento_google");

                    b.Property<decimal>("VlrInvestimentoMeta")
                        .HasColumnType("numeric(38,2)")
                        .HasColumnName("vlr_investimento_meta");

                    b.ToTable("lancamento_varejo", "ida");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("Cargos")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.ClienteModeloControle", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ModeloControle", "ModeloControle")
                        .WithMany("ClientesModelosControles")
                        .HasForeignKey("IdModeloControle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ModeloControle");
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Lancamento", b =>
                {
                    b.HasOne("backend.Models.ModeloControle", "ModeloControle")
                        .WithMany()
                        .HasForeignKey("IdModeloControle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloControle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.HasOne("backend.Models.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.HasOne("backend.Models.Aplicacao", "Aplicacao")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdAplicacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("backend.Models.Usuario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("backend.Models.UsuarioArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("UsuariosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("UsuariosAreas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.LancamentoCadastro", b =>
                {
                    b.HasOne("backend.Models.Lancamento", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.LancamentoCadastro", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.LancamentoSaude", b =>
                {
                    b.HasOne("backend.Models.Lancamento", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.LancamentoSaude", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.LancamentoVarejo", b =>
                {
                    b.HasOne("backend.Models.Lancamento", null)
                        .WithOne()
                        .HasForeignKey("backend.Models.LancamentoVarejo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("UsuariosAreas");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("ClientesCargos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("ClientesCargos");

                    b.Navigation("ClientesUsuarios");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("backend.Models.ModeloControle", b =>
                {
                    b.Navigation("ClientesModelosControles");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("ClientesUsuarios");

                    b.Navigation("UsuariosAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
