// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ida")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5117),
                            Nome = "Página Inicial"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5119),
                            Nome = "Dashboard"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5120),
                            Nome = "Gerenciamento de Cliente"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5121),
                            Nome = "Gerenciamento de Pessoa"
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5122),
                            Nome = "Gerenciamento de Cargo"
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5123),
                            Nome = "Gerenciamento de Área"
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5125),
                            Nome = "Gerenciamento de Usuário"
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5126),
                            Nome = "Relatórios"
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5127),
                            Nome = "Configurações"
                        });
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5360),
                            Nome = "Administração"
                        });
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5328),
                            IdRole = 1L,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCargo");

                    b.ToTable("cargo_area", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5424),
                            IdArea = 1L,
                            IdCargo = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.ToTable("cliente", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cnpj = "00000000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5286),
                            Email = "suporte@analytica.com",
                            Nome = "Analytica IDA",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_cargo", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5394),
                            IdCargo = 1L,
                            IdCliente = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("cliente_usuario", "ida");
                });

            modelBuilder.Entity("backend.Models.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DadosAntigos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("log_auditoria", "ida");
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdUsuarioDestino")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("notificacao", "ida");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("pessoa", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = "00000000000",
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5458),
                            Email = "suporte@analytica.com",
                            IdCliente = 1L,
                            Nome = "Administrador",
                            Telefone = "00000000000"
                        });
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("role", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(4759),
                            Nome = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(4764),
                            Nome = "proprietário"
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(4765),
                            Nome = "supervisor"
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(4767),
                            Nome = "vendedor"
                        });
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IdAplicacao")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdRole");

                    b.ToTable("role_aplicacao", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5183),
                            IdAplicacao = 1L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5185),
                            IdAplicacao = 2L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5186),
                            IdAplicacao = 3L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 4L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5187),
                            IdAplicacao = 4L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 5L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5188),
                            IdAplicacao = 5L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 6L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5189),
                            IdAplicacao = 6L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 7L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5190),
                            IdAplicacao = 7L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 8L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5192),
                            IdAplicacao = 8L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 9L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5193),
                            IdAplicacao = 9L,
                            IdRole = 1L
                        },
                        new
                        {
                            Id = 10L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5194),
                            IdAplicacao = 1L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 11L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5195),
                            IdAplicacao = 2L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 12L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5195),
                            IdAplicacao = 4L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 13L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5196),
                            IdAplicacao = 5L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 14L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5202),
                            IdAplicacao = 6L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 15L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5202),
                            IdAplicacao = 7L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 16L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5203),
                            IdAplicacao = 8L,
                            IdRole = 2L
                        },
                        new
                        {
                            Id = 17L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5204),
                            IdAplicacao = 1L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 18L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5205),
                            IdAplicacao = 2L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 19L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5206),
                            IdAplicacao = 4L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 20L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5207),
                            IdAplicacao = 7L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 21L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5208),
                            IdAplicacao = 8L,
                            IdRole = 3L
                        },
                        new
                        {
                            Id = 22L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5209),
                            IdAplicacao = 1L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 23L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5210),
                            IdAplicacao = 2L,
                            IdRole = 4L
                        },
                        new
                        {
                            Id = 24L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 20, 29, 54, 807, DateTimeKind.Utc).AddTicks(5211),
                            IdAplicacao = 8L,
                            IdRole = 4L
                        });
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DtUltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FlAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IdArea")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCargo")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdCargo");

                    b.ToTable("usuario", "ida");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DtUltimaAtualizacao = new DateTime(2026, 2, 21, 17, 29, 54, 807, DateTimeKind.Local).AddTicks(5512),
                            FlAtivo = true,
                            IdArea = 1L,
                            IdCargo = 1L,
                            Login = "admin",
                            Senha = "$2a$11$z11Fa2ah3dUFm.KSHnxBseVk4.0D8XYxr75/8lGQkMc4A/v6AxofO"
                        });
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("Cargos")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.CargoArea", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("CargosAreas")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("backend.Models.ClienteCargo", b =>
                {
                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesCargos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.ClienteUsuario", b =>
                {
                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("ClientesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Notificacao", b =>
                {
                    b.HasOne("backend.Models.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.Models.RoleAplicacao", b =>
                {
                    b.HasOne("backend.Models.Aplicacao", "Aplicacao")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdAplicacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("RolesAplicacoes")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("backend.Models.Usuario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("backend.Models.Aplicacao", b =>
                {
                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Area", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Navigation("CargosAreas");

                    b.Navigation("ClientesCargos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("ClientesCargos");

                    b.Navigation("ClientesUsuarios");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("backend.Models.Pessoa", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("RolesAplicacoes");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("ClientesUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
